name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes Cypress
        run: npx cypress run --record --video --headless --no-exit || echo "Testes falharam, verificando logs..."

      # Passo para autenticação OIDC (necessário para obtenção de ID Token)
      - name: Autenticar com OIDC
        id: oidc_auth
        run: |
          echo "ACTIONS_ID_TOKEN_REQUEST_URL=${ACTIONS_ID_TOKEN_REQUEST_URL}" >> $GITHUB_ENV
          echo "ACTIONS_ID_TOKEN_REQUEST_URL is set"
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}

      - name: Criar attestation do build
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "cypress/videos/"
          push-to-registry: false
          show-summary: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Armazenar vídeos e screenshots (se falhar)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/
            cypress/screenshots/
          if-no-files-found: ignore
